# Generated by Django 3.0.3 on 2020-03-03 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='タスク')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='完了日時')),
            ],
        ),
    ]
